import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DrinkSearchResult from "../components/DrinkSearchResult";

export default function Home() {
  const [searchResults, setSearchResults] = useState([]);
  const searchHandler = async (input) => {
    const req = await fetch(
      `https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${input}`
    );

    const data = await req.json();

    const { drinks } = data;
    setSearchResults(drinks);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.inputContainer}>
        <Image
          src="/../public/thirsty.png"
          alt=""
          width="300px"
          height="400px"
          minWidth="300px"
          minHeight="400px"
        />
        <input
          className={styles.input}
          onChange={(e) => searchHandler(e.target.value)}
        />
        {searchResults?.map((drink) => {
          // return <li key={result?.strDrink}>{result?.strDrink}</li>;
          return <DrinkSearchResult drink={drink} key={drink?.strDrink} />;
        })}
      </div>
    </div>
  );
}
